ReviewerProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReviewerProject.Models;
using ReviewerProject.CustomAttribute;

namespace ReviewerProject.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View(db.Jobs.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [AuthorizeOrRedirectAttribute(Roles = "Site Admin")]
        public ActionResult Admin()
        {
            return View();
        }

        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult GameElementAdmin()
        {
            return View();
        }

    }
}

ReviewerProject/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReviewerProject.Models;
using ReviewerProject.CustomAttribute;

namespace ReviewerProject.Controllers
{
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Index()
        {
            return View(db.Jobs.ToList());
        }

        public ActionResult ListJobs()
        {
            return View(db.Jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Create([Bind(Include = "ID,JobName,BaseHP,BaseAP,BaseLoad,Description,JobProficiencies")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: Jobs/Edit/5
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Edit([Bind(Include = "ID,JobName,BaseHP,BaseAP,BaseLoad,Description,JobProficiencies")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReviewerProject/Controllers/QuestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReviewerProject.Models;
using ReviewerProject.CustomAttribute;

namespace ReviewerProject.Controllers
{
    public class QuestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Quests
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Index()
        {
            return View(db.Quests.ToList());
        }

        public ActionResult ListQuests()
        {
            return View(db.Quests.ToList());
        }

        // GET: Quests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quest quest = db.Quests.Find(id);
            if (quest == null)
            {
                return HttpNotFound();
            }
            return View(quest);
        }

        // GET: Quests/Create
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Create([Bind(Include = "ID,Title,StarLevel,Time")] Quest quest)
        {
            if (ModelState.IsValid)
            {
                db.Quests.Add(quest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quest);
        }

        // GET: Quests/Edit/5
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quest quest = db.Quests.Find(id);
            if (quest == null)
            {
                return HttpNotFound();
            }
            return View(quest);
        }

        // POST: Quests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Edit([Bind(Include = "ID,Title,StarLevel,Time")] Quest quest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quest);
        }

        // GET: Quests/Delete/5
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quest quest = db.Quests.Find(id);
            if (quest == null)
            {
                return HttpNotFound();
            }
            return View(quest);
        }

        // POST: Quests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Site Admin,Game Element Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Quest quest = db.Quests.Find(id);
            db.Quests.Remove(quest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReviewerProject/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReviewerProject.Models;
using Microsoft.AspNet.Identity;

namespace ReviewerProject.Controllers
{
    public class ThreadsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        // GET: Threads
        public ActionResult Index()
        {
            return View(db.Threads.ToList());
        }

        public ActionResult AdminBugFixesList()
        {
            return View(db.Threads.ToList());
        }

        public ActionResult AdminReviewList()
        {
            return View(db.Threads.ToList());
        }

        public ActionResult ListThreads()
        {
            return View(db.Threads.ToList());
        }

        public ActionResult BugFixesList()
        {
            return View(db.Threads.ToList());
        }

        public ActionResult ReviewList()
        {
            return View(db.Threads.ToList());
        }


        public ActionResult ListOfThreadsByUser(string ID, string sortOrder, string searchString)
        {
            ViewBag.TitleSortParam = String.IsNullOrEmpty(sortOrder) ? "username_asc" : "";
            //var threads = db.Threads
            //    .Where(a => a.User.Id == ID)
            //    .ToList();

            var threads = from u in db.Threads
                           select u;

            var user = db.Users.Find(ID);

            if (!String.IsNullOrEmpty(searchString))
            {
                threads = threads.Where(u => u.Title.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "username_asc":
                    threads = threads.OrderBy(u => u.Title);
                    break;
            }

            ViewBag.UserName = user.UserName;
            return View(threads.Where(a => a.User.Id == ID));
        }

        // GET: Threads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // GET: Threads/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Threads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ThreadType,CategoryType,UserID")] Thread thread)
        {
            if (ModelState.IsValid)
            {
                thread.UserID = User.Identity.GetUserId();
                db.Threads.Add(thread);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thread);
        }

        // GET: Threads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // POST: Threads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ThreadType,CategoryType")] Thread thread)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thread).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thread);
        }

        // GET: Threads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // POST: Threads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Thread thread = db.Threads.Find(id);
            db.Threads.Remove(thread);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

ReviewerProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home</title>

    <!-- core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">
    <link href="~/Content/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/main.css" rel="stylesheet">
    <link href="~/Content/responsive.css" rel="stylesheet">
</head><!--/head-->
<br />
<br />
<br />
<h2 class="center">The Jacqueline Radtke Development Team</h2>

<div class="container center wow fadeInDown">
    <img src="~/Content/Images/About Us.jpg" alt="About Us" class="floatLeft" />
    <p>
        We are a small development team that put together a guide for all of you hard working explorers out there!
        When you're roaming the big open world and have questions, you should know where to look with us! We have a large
        selection of information to help you out! Our only goal is give you the right information as quickly as possible.
        If you have any questions head to our forum. We have moderators there to to make sure that content is safe and
        helpful. Or send us and email and we'll make sure to make any changes or help you as best we know how.
    </p>
    <p>
        We are welcoming of your feedback and appreciate it if your willing to send us something! We'd love to hear from you!
    </p>
</div>

<script src="~/Scripts/jquery.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.prettyPhoto.js"></script>
<script src="~/Scripts/jquery.isotope.min.js"></script>
<script src="~/Scripts/main.js"></script>
<script src="~/Scripts/wow.min.js"></script>

ReviewerProject/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home</title>

    <!-- core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">
    <link href="~/Content/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/main.css" rel="stylesheet">
    <link href="~/Content/responsive.css" rel="stylesheet">
</head><!--/head-->
<br />
<br />
<br />
<h1>Admin</h1>

<div class="row">
    <div>
        <div>
            <h2>Thread Info</h2>
            @Html.ActionLink("Click here for a list of Threads.", "Index", "Threads")
        </div>
        <div>
            <h2>Thread Comments</h2>
            @Html.ActionLink("Click here for a list of threads and their comments.", "Index", "ThreadComments")
        </div>
        <div>
            <h2>Users</h2>
            @Html.ActionLink("Click here for a list of all users.", "Index", "Account")
        </div>
        <div>
            <h2>User Roles</h2>
            @Html.ActionLink("Click here for a list of all user roles.", "Index", "IdentityRole")
        </div>
        <div>
        <h2>Game Tips</h2>
            @Html.ActionLink("Click here for a list of all game tips.", "Index", "GameTips")
        </div>
        <div>
            <h2>Abilities Info</h2>
            @Html.ActionLink("Click here for a list of Abilites.", "Index", "Abilities")
        </div>
        <div>
            <h2>Eidolons Info</h2>
            @Html.ActionLink("Click here for a list of Eidolons.", "Index", "Eidolons")
        </div>
        <div>
            <h2>Equipment Info</h2>
            @Html.ActionLink("Click here for a list of Equipment.", "Index", "Equipments")
        </div>
        <div>
            <h2>Jobs Info</h2>
            @Html.ActionLink("Click here for a list of Jobs.", "Index", "Jobs")
        </div>
        <div>
            <h2>Materials Info</h2>
            @Html.ActionLink("Click here for a list of Materials.", "Index", "Materials")
        </div>
        <div>
            <h2>Monsters Info</h2>
            @Html.ActionLink("Click here for a list of Monsters.", "Index", "Monsters")
        </div>
        <div>
            <h2>Quests Info</h2>
            @Html.ActionLink("Click here for a list of Quests.", "Index", "Quests")
        </div>
    </div>
</div>

ReviewerProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home</title>

    <!-- core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">
    <link href="~/Content/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/main.css" rel="stylesheet">
    <link href="~/Content/responsive.css" rel="stylesheet">

    @* Code from W3schools tutorials *@
    @* http://www.w3schools.com/googleapi/google_maps_basic.asp *@
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <script>
        function initialize() {
            var mapProp = {
                center: new google.maps.LatLng(44.7646836, -85.5843242),
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head><!--/head-->
<br />
<br />
<br />
<br/>
<br/>
<br/>

<h2>Contact</h2>

<p>Feel free to contact us anytime! We're available at all times of the day!</p><br/>

<address>
    NorthWestern Michigan College<br />
    Traverse City, MI 49626<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<body>
    <div id="googleMap" style="width:500px;height:380px;"></div>
</body>

<div class="col-md-4 col-sm-12">
    <div class="contact-form">
        <h2>Send a message</h2>
        <form id="main-contact-form" name="contact-form" method="post" action="sendemail.php">
            <div class="form-group">
                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
            </div>
            <div class="form-group">
                <input type="email" name="email" class="form-control" required="required" placeholder="Email Id">
            </div>
            <div class="form-group">
                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your text here"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-submit" value="Submit">
            </div>
        </form>
    </div>
</div>

ReviewerProject/Views/Home/GameElementAdmin.cshtml
@{
    ViewBag.Title = "GameElementAdmin";
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home</title>

    <!-- core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">
    <link href="~/Content/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/main.css" rel="stylesheet">
    <link href="~/Content/responsive.css" rel="stylesheet">
</head><!--/head-->
<br />
<br />
<br />
<h2>Game Element Admin</h2>

<div class="row">
    <div>
        <div>
            <h2>Abilities Info</h2>
            @Html.ActionLink("Click here for a list of Abilites.", "Index", "Abilities")
        </div>
        <div>
            <h2>Eidolons Info</h2>
            @Html.ActionLink("Click here for a list of Eidolons.", "Index", "Eidolons")
        </div>
        <div>
            <h2>Equipment Info</h2>
            @Html.ActionLink("Click here for a list of Equipment.", "Index", "Equipments")
        </div>
        <div>
            <h2>Jobs Info</h2>
            @Html.ActionLink("Click here for a list of Jobs.", "Index", "Jobs")
        </div>
        <div>
            <h2>Materials Info</h2>
            @Html.ActionLink("Click here for a list of Materials.", "Index", "Materials")
        </div>
        <div>
            <h2>Monsters Info</h2>
            @Html.ActionLink("Click here for a list of Monsters.", "Index", "Monsters")
        </div>
        <div>
            <h2>Quests Info</h2>
            @Html.ActionLink("Click here for a list of Quests.", "Index", "Quests")
        </div>
    </div>
</div>